language: node_js
before_script:
  - npm i api2html -g
script:
  - api2html -o test.html docs/swagger.yaml
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master