# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
- script: npm install api2html -g
- script: 
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
- script: api2html -o docs/shins.html -b -s -c "images/Vipps Logo@3x.png" docs/swagger.yaml
- script: 
    git status
    git add docs/shins.html
    git commit -m "Azure api2html conversion"
    git remote -v
    git push -u origin gh-pages

