# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  action-filter:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: files-filter
      uses: wcchristian/gh-pattern-filter-action@master
      with:
        args: .*\\.yaml$
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ 12.x }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install widdershins -g
    - run: widdershins --help
      env:
        CI: true
    - name: Deploy to GitHub Pages
      uses: docker://maxheld83/ghpages@v0.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_DIR: test-documentation/build/
