# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: 
    - '.github/**' 
    - 'docs/swagger.yaml'
  pull_request:
    branches: [ master ]

jobs:
  action-filter:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: actions/cache@v1
      with:
        path: ../slate/vendor/bundle
        key: ${{ runner.os }}-slate-
    - name: Install and run Widdershins
      run: |
        npm install widdershins -g
        widdershins ./docs/swagger.yaml -o docs/index.html.md
    - name: Install Slate
      run: |
        git init ../slate
        cd ../slate
        gem install bundler:2.0.2
        bundle config path ./vendor/bundle
        git pull https://github.com/slatedocs/slate
        bundle install
    - name: Python find replace
      run: |
        cd ./docs/
        python find_replace.py
    - name: Build Slate
      run: |
        cp ./docs/index.html.md ../slate/source/index.html.md
        cd ../slate
        bundle exec middleman build --clean
    - name: Push new build
      run: |
        ls
        cp -R ../slate/build ./docs/
        git config --local user.email "actions@example.com"
        git config --local user.name "github actions"
        git remote -v
        git branch -a
        git add ./docs
        git commit -m "fun"
        git push
      env:
        CI: true
